package StudentPortal::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'StudentPortal::Schema',
    
    connect_info => {
        # TODO veci z configu
        dsn => 'dbi:mysql:ewpportal',
        user => 'ewpportal',
        password => 'ewpportal',
        AutoCommit => q{1},
        mysql_enable_utf8 => 1
    }
);

=head1 NAME

StudentPortal::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<StudentPortal>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<StudentPortal::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Jan Konstant

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
